### ISSUE TITLE
Could careers.m.o be a static site?

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#321]
Since we've gradually removed all dynamic functionality (LocalizationMiddleware, Django Admin) from careers.m.o I'm thinking how we can convert this to a static website to simplify deployments.

I don't think it's worth investing in converting this to something else than Django, since we have a working dev flow and the connection to Greenhouse. Ideally I would like to trigger a CI job to crawl a locally hosted version of the site and upload the resulting files to S3. Then have CloudFront in front it. 

This setup can completely run on Travis / Jenkins, S3 and CloudFront and we would remove all k8s deployments / ELBs etc. It will also get another app off Deis.

@pmac I remember you did some research on django converters to static. Can you please point me to the results?

@jpetto @jgmize @metadave @pmac would like your feedback on this

**Comment by jgmize** [comment]
I'm very much in favor of this.

**Comment by glogiotatidis** [comment]
Thanks for the feedback @pmac 

> Medusa is still the most straight-forward and least magical of the Django generators I've found.

That makes me wonder, why not use a website "downloader" like `wget` or the more sophisticated [httptrack](https://www.httrack.com/)?

The following commands seems to do the trick for careers (minus 3 video thumbnails which are added via JS)

```
$ httrack https://careers.mozilla.org --keep-alive --near "-*" "+https://careers.mozilla.org/*"
```

**Comment by pmac** [comment]
if that works for careers then great. It wouldn't work for bedrock because a) it's just too large a site to feel confident it found everything, and b) there are many orphaned pages and sections of the site with no links to them from anywhere (many are in-product direct links). So I was hoping we could find something that would work a bit more universally, similarly to how we can build a sitemap. But if this gets it done quickly then great.

**Comment by glogiotatidis** [comment]
Fair enough. I think `wget` would work for lumbergh. I'll give a try soonish  :leaves:

**Comment by metadave** [comment]
great idea, I think we could save some $$$ here.

**Comment by glogiotatidis** [comment]
We all agree that this is a good idea. Filed #327 to make it happen.

Thanks for you input all!
