### ISSUE TITLE
Replace link to air.m.o?

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#329]
Front page links to air.mozilla.org which has been replaced by airmo.mozilla.org. The later requires login so I guess it doesn't make sense to replace one URL with the other.

Thoughts and ideas @bensternthal @stephaniehobson ?

**Comment by bensternthal** [comment]
Good find.

I think this should be removed,  we can see if HR has some thoughts on a replacement. Part of me wants to link to https://www.youtube.com/user/Mozilla I really like the "people of mozilla" series.

**Comment by stephaniehobson** [comment]
Eeep, what an awful user experience.

I'll remove it for now.

There's a meeting on Tuesday with the team. I'll bring it up with them.

**Comment by glogiotatidis** [comment]
Fixed in prod!
