### ISSUE TITLE
videos on homepage loading from videos.cdn.mozilla.net are 404

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/lumbergh#334]
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1489692 and also [issue](https://github.com/mozilla/bedrock/issues/6187) affecting bedrock.

**Comment by glogiotatidis** [comment]
@bensternthal did you mean https://bugzilla.mozilla.org/show_bug.cgi?id=1489692?

**Comment by bensternthal** [comment]
Yep, filing bugs before coffee..

**Comment by jgmize** [comment]
fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1489692#c19
