### ISSUE TITLE
Include robots.txt and crontibute.json to the static site dump

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#341]

**Comment by glogiotatidis** [comment]
I'm wondering whether `contribute.json` is something that we still push fwd? It's minimal effort to include this but only if it adds value.

What do you think folks? @mozmeao/theconn

**Comment by jpetto** [comment]
IMO keeping it around is the Mozilla way.

**Comment by pmac** [comment]
It is still a thing, and I think for Mozilla properties the TLS Observatory will look for one. It's not critical clearly, but doesn't hurt to keep IMHO.

**Comment by glogiotatidis** [comment]
Good! I'll update and include
