### ISSUE TITLE
Connect with Greenhouse to trigger regeneration of the static site on every update

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#344]
Ideally instead of running periodically #343 we want get triggered by GH every time a listing get updates

- [x] Stage
- [x] Production

**Comment by glogiotatidis** [comment]
Created a webook from Greenhouse to Netlify on [`Job Post updated`](https://developers.greenhouse.io/webhooks.html#job-post-updated) event to test how this works. Note that these changes are in my personal netlify acc and will need to get migrated when and if we decide to settle with netlify.

**Comment by metadave** [comment]
would it be useful to have a _simple_ way to manually trigger as well?

**Comment by pmac** [comment]
you can manually trigger a netlify build anytime you like via their web console or cli tool

**Comment by pmac** [comment]
we'd just need to signup for a pro account and setup the site in that team so we could all manage it.

**Comment by pmac** [comment]
and I assume we can setup an automated build and deploy from a github branch as well? `prod` perhaps? With `master` going to a staging deployment?

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/issues/1017

**Comment by glogiotatidis** [comment]
> and I assume we can setup an automated build and deploy from a github branch as well? `prod` perhaps? With `master` going to a staging deployment?

Agreed

**Comment by glogiotatidis** [comment]
- Updated the Netlify webhook to build `careers.allizom.org` on netlify.
- Created GitLab CI job to trigger rebuild daily
- Created DMS to monitor the daily rebuild

Will leave this open to do the same for production

**Comment by glogiotatidis** [comment]
Done for production too

**Comment by glogiotatidis** [comment]
* Updated Greenhouse to ping Gitlab on `Job Update` to build `production` and `master` branches
