### ISSUE TITLE
careers.mozilla.org - 'people page' copy revisions to 'How we take care of our people' section

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#351]
| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | 1 |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: The copy in the 'How we take care of our people' section on careers.mozilla.org is out of date and needs to be align with the current verbiage in use.
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The page is updated with new copy (and all the old, incorrect copy removed)
- [ ] The pdf describing benefits, comp, etc. is uploaded to assets.mozilla.org
- [ ] The pdf is link to in the page copy as in the design
- [ ] Clicks on the pdf are tracked in GA

**Comment by ejregithub** [comment]
@alexgibson - flagged this one for you, please. It is a P1 to get the current, incorrect copy removed with the 'interim' copy and design in place.

The [mockup](https://docs.google.com/presentation/d/1N7GBhz2RpLwag49KHYZEtDBivCTTuJw3sYe1Zm9cTIU/edit#slide=id.g45bb20216e_1_0) is rough (JRouse and I spent minimum time on it), your best judgement on layout/alignment and sticking with the current page font, etc. please.

Here's the pdf brochure we need to upload/link to in the page.
[MOZ_1802_Comp-Brochure_04-DIGITAL.pdf](https://github.com/mozmeao/lumbergh/files/2563271/MOZ_1802_Comp-Brochure_04-DIGITAL.pdf)

**Comment by ejregithub** [comment]
@alexgibson - we should also look to track this, clicks on the pdf, in GA.   Please reach out to Robert Winters @ Analytics Pros if needed.

**Comment by alexgibson** [comment]
Opened a PR for this here, everything should hopefully be in place: https://github.com/mozmeao/lumbergh/pull/353

**Comment by ejregithub** [comment]
@alexgibson - This looks great, thank you. I will pass to Mardi for final stakeholder approval.

**Comment by ejregithub** [comment]
@alexgibson - from Mardi: 
- [ ] please swap the heart icon for the star icon 
![screen shot 2018-11-07 at 4 43 36 pm](https://user-images.githubusercontent.com/20547886/48277275-0da6c900-e3ff-11e8-9428-3876ae91fce5.png)
- [ ] Center align the copy and Learn more CTA to match the "What makes us… us." section alignment, just above.

We're good to ship with those tweaks.

**Comment by glogiotatidis** [comment]
This is now in production :ship:
