### ISSUE TITLE
Replace icon fonts with SVG

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/lumbergh#352]
When viewing careers on Firefox Focus (with web fonts disabled), all the icon fonts show up as rather comical emoji 🌮 

When we rebuild the site / pages, we should switch from icon fonts to SVG instead. We could also find a slightly nicer fallback font stack too.

![icon-fonts-1](https://user-images.githubusercontent.com/400117/48252494-cd464b80-e3fc-11e8-970c-eed619b3d573.jpg)
![icon-fonts-2](https://user-images.githubusercontent.com/400117/48252497-cf100f00-e3fc-11e8-991e-a108b800dc61.jpg)

**Comment by glogiotatidis** [comment]
With the new site redesign this is not longer valid. Thanks for reporting! :cake:
