### ISSUE TITLE
Add security headers

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#362]
Evaluate and add security headers to the statically hosted version of the site. 

Headers as served the current k8s hosted version of the Django site
```
Server: meinheld/0.6.1
Date: Fri, 11 Jan 2019 10:11:43 GMT
Content-Type: text/html; charset=utf-8
Content-Security-Policy: font-src 'self' http://*.mozilla.net https://*.mozilla.net http://*.mozilla.org https://*.mozilla.org; img-src 'self' data: http://*.mozilla.net https://*.mozilla.net http://*.mozilla.org https://*.mozilla.org http://www.google-analytics.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' http://*.mozilla.org https://*.mozilla.org http://*.mozilla.net https://*.mozilla.net; script-src 'self' data: http://*.mozilla.org https://*.mozilla.org http://*.mozilla.net https://*.mozilla.net http://www.google-analytics.com https://www.google-analytics.com http://www.googletagmanager.com https://www.googletagmanager.com; default-src 'self' *.cdn.mozilla.net assets.mozilla.net
X-Frame-Options: SAMEORIGIN
Content-Length: 21015
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
X-Backend-Server: careers-prod-web-547f8f4bbb-wfbhk.careers-prod.frankfurt.moz.works
Connection: Keep-Alive
```

**Comment by glogiotatidis** [comment]
Implemented the same headers we have now on Netlify in #359.

Our CSP policy is very lax though and iirc this is b/c of googletagmanager. Is there a better way to deal with that? I see that bedrock suffer from the same issue. /cc @pmac?

**Comment by pmac** [comment]
There are some more modern CSP techniques that we could use to lock it down further. We could potentially use the [strict-dynamic](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic) directive for script-src that would allow us to make script-src stronger while still allowing the tag manager script to load what it needs.

**Comment by glogiotatidis** [comment]
> There are some more modern CSP techniques that we could use to lock it down further. We could potentially use the [strict-dynamic](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic) directive for script-src that would allow us to make script-src stronger while still allowing the tag manager script to load what it needs.

Got it, thanks. 

Let's keep it as is for now to push fwd with the static convention and we can revisit in the future
