### ISSUE TITLE
Add build monitors

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#363]
We need a way to monitor that the build are happening.

Probably we can re-use the DM Snitches we have already setup for careers APScheduler.  

- [x] Stage
- [ ] Production

**Comment by glogiotatidis** [comment]
Added DMS snitch to monitor the daily rebuild for staging.

https://deadmanssnitch.com/snitches/d216258591/setup

Will do the same for prod

**Comment by glogiotatidis** [comment]
Done for prod, same gitlab schedule, same DMS snitch

**Comment by metadave** [comment]
@glogiotatidis can you add some troubleshooting notes [here](https://deadmanssnitch.com/snitches/d216258591/edit)? Why are stage/prod sharing a snitch?

**Comment by pmac** [comment]
@metadave ooo... I know this one. It's because they share a single daily schedule that runs in GitLab. See [this file](https://github.com/mozmeao/lumbergh/blob/master/.gitlab-ci.yml)

**Comment by pmac** [comment]
My main question is whether we should keep the snitch ID and API URLs for all of that secret? Can just add them as variables in the GitLab UI.

**Comment by metadave** [comment]
@pmac yes please

**Comment by pmac** [comment]
@glogiotatidis I guess if we're going to make them secret then we should ditch these now that they're public.

**Comment by glogiotatidis** [comment]
> My main question is whether we should keep the snitch ID and API URLs for all of that secret? Can just add them as variables in the GitLab UI.

that's a good idea, will update asap

**Comment by glogiotatidis** [comment]
> @glogiotatidis can you add some troubleshooting notes [here](https://deadmanssnitch.com/snitches/d216258591/edit)?

done

**Comment by glogiotatidis** [comment]
Updated netlify and DMS webhooks and moved them to env variables
