### ISSUE TITLE
Support documentation

### ISSUE THREAD

**Issue by metadave** [mozmeao/lumbergh#365]
- include a checklist to help when Things Go Wrong

**Comment by glogiotatidis** [comment]
Also update mana

**Comment by glogiotatidis** [comment]
Updated mana https://mana.mozilla.org/wiki/display/EN/careers.mozilla.org

**Comment by glogiotatidis** [comment]
Added docs in https://github.com/mozmeao/lumbergh/pull/410 and a debugging checklist in the mana page. 

@metadave r?

**Comment by metadave** [comment]
:+1:
