### ISSUE TITLE
Change DNS to point to the new static endpoint

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#369]
- [x] Staging - careers.allizom.org
- [x] Production - careers.mozilla.org

**Comment by glogiotatidis** [comment]
Changed `careers-stage.moz.works` to CNAME Netlify. 

Then Netlify required `<10 minutes` to get the new DNS record and fetch a proper LetsEncrypt cert for the the site.

Meanwhile users would get security errors as expected.

For production we can
 - Use LetsEncrypt to generate a cert for `careers.mozilla.org`
 - Upload the cert to Netlify before making the change
 - Make the DNS switch
 - Request from Netlify for generate it's own LetsEncrypt cert.

thoughts @mozmeao/theconn ?

**Comment by metadave** [comment]
@glogiotatidis that sounds like it should work. Let's figure out who to notify on the business side and schedule a date/time.

Should we continue to run lumbergh K8s infra for a few weeks Just In Case?

**Comment by glogiotatidis** [comment]
> @glogiotatidis that sounds like it should work.

let me try the letsencrypt trick first.

> Should we continue to run lumbergh K8s infra for a few weeks Just In Case?

Yes, lets decom a month after the switch. Will add a reminder

**Comment by glogiotatidis** [comment]
> > @glogiotatidis that sounds like it should work.
> 
> let me try the letsencrypt trick first.

Success! :smiley: 

I fetched a Let'sEncrypt certificate for careers.mozilla.org with the following steps:
 1. Set the HPA for `careers-prod.web` to 1 pod for both `min` and `max` in `oregon-b` (didn't touch frankfurt)
 2. Created  https://github.com/glogiotatidis/lumbergh/commit/216eb7e969ca1d2abb8c425e0719fe7d0f61a81f to serve `.well-known/acme-challenge/` URLs with Django
 3. Pushed docker image with (2) in `oregon-b` 
 4. Got into the running pod in `oregon-b` and used [acme.sh](https://github.com/Neilpang/acme.sh/blob/master/acme.sh) to fetch a cert with the command `./acme.sh --issue -d careers.mozilla.org -w /app`
 5. Copied the generated files to my local machine
 6. Uploaded cert, key and fullchain to Netlify.
 7. Verified that key was correctly installed on Netlify.
 8. Pushed previous docker image to `oregon-b`
 9. Set the HPA to default values for site.

Next steps:
 1. The cert is valid for 3 months which gives us plenty of time to switch
 2. Netlify provides a button to use `Letsencrypt`, so after we make the switch we need to click the button. Created issue #392 to track this.

**Comment by glogiotatidis** [comment]
We're now live \o/! 

Linked issue https://github.com/mozmeao/infra/issues/1053

hint: We finally used S3 / Cloudfront instead of Netlify
