### ISSUE TITLE
Configure netlify to build `master` and `production` branches

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#381]

**Comment by glogiotatidis** [comment]
Since we're not using Netlify DNS we need to create two Netlify sites, one for `careers.allizom.org` (stage) and one for `careers.mozilla.org` (prod)

**Comment by glogiotatidis** [comment]
Prod: https://app.netlify.com/sites/mozilla-careers/overview
Stage: https://app.netlify.com/sites/mozilla-careers-stage/overview

**Comment by pmac** [comment]
Ah... it's interesting that we needed a separate app for stage. I'm guessing that's required because the sites use different domains? I guess that does keep it clean, and does allow us to use some auth on the non-prod site since that seems to be a site-wide setting. Nice work 👍

**Comment by glogiotatidis** [comment]
> Ah... it's interesting that we needed a separate app for stage. I'm guessing that's required because the sites use different domains? I guess that does keep it clean, and does allow us to use some auth on the non-prod site since that seems to be a site-wide setting. Nice work +1

Yes. We could take the "a subdomain per branch"  route but would required to use Netlify's DNS to work. It's a bit of double work but it's not too much work, so two apps it looks like the way to go. 

Do you think we should be adding auth in front of staging @pmac?

**Comment by pmac** [comment]
> Do you think we should be adding auth in front of staging @pmac?

No I don't. It did come up in one of our meetings with them, but it's not something I'm expecting we'll use. I just wanted to point out that this method does allow us to do it if need be though.
