### ISSUE TITLE
Adding Fast Co Most Innovative Company Logos to Mozilla Career site 

### ISSUE THREAD

**Issue by dianel** [mozmeao/lumbergh#393]
Please add in Fast Co #3 (security) and #49 (overall) logos to careers.mozilla.org top right corner.

Logo usage guide + logo:

[Fast Company's Most Innovative Companies logo usage guide.pdf](https://github.com/mozmeao/lumbergh/files/2886398/Fast.Company.s.Most.Innovative.Companies.logo.usage.guide.pdf)

[fastcompanylogoscustomizedfor3insecurityand49in.zip](https://github.com/mozmeao/lumbergh/files/2886399/fastcompanylogoscustomizedfor3insecurityand49in.zip)

**Comment by bensternthal** [comment]
Received this request via email and asked this to be posted here to work out questions.

A few things we are checking on:

- [ ] Is our license all sorted and this usage is OK.
- [ ] Reviewing with brand team

**Comment by dianel** [comment]
Per #1 - "Yes we got the non profit rate and went for the cheaper package that just excludes use in adverts, I believe it was $3200 for a year."
Per #2 - Can you clarify what you mean here?

**Comment by bensternthal** [comment]
I reached out to Tim for advice on placement, we both agree it is appropriate for the footer. Will get to this next week.

**Comment by dianel** [comment]
it will get lost in the footer won't it?
