### ISSUE TITLE
 Add Corporate Equality Index logo to bottom of careers site next to Fast Co logos

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/lumbergh#403]
See [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1539987)

**Comment by glogiotatidis** [comment]
We're trying to find a higher res logo. 

/remind me to check in 10 days

**Comment by glogiotatidis** [comment]
@bensternthal any updates here? do we still want to do this?

**Comment by bensternthal** [comment]
Still waiting on an image that is acceptable. I ping'd in the bug today. If we don't hear back in a week we can close this for now.

/remind me to check on friday

**Comment by bensternthal** [comment]
Diane confirmed in the bug that she could not get an acceptable image. Closing this out for now.
