### ISSUE TITLE
"Apply for this job" button has a visible line through it (bug  1541437)

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#404]
Reported on Bugzilla
Tested https://careers.mozilla.org/position/gh/1589555/ in Firefox and Safari.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1541437

**Comment by jpetto** [comment]
Context for posterity: the alignment bug occurs when the locations list is long. The button has a `bottom` position specified, so the longer the location list, the further down the apply button will appear. Will fix by specifying `top` position rather than `bottom`.
