### ISSUE TITLE
[UX/UI] mozilla logo display bug when resizing from tablet -> mobile

### ISSUE THREAD

**Issue by jpetto** [mozmeao/lumbergh#406]
When resizing the page from tablet down to mobile, the Mozilla logo has incorrect top padding.

<img width="651" alt="Screen Shot 2019-04-08 at 9 46 40 AM" src="https://user-images.githubusercontent.com/317532/55733450-7b254880-59e3-11e9-941d-513dd989bfd4.png">

This top padding is [applied via JS through a `resize` handler](https://github.com/mozmeao/lumbergh/blob/master/careers/base/static/js/base.js#L199) - that's probably the place to start looking.

**Comment by glogiotatidis** [comment]
With the new site redesign this is not longer valid. Thanks for reporting! :cake:
