### ISSUE TITLE
[UX/UI] nav overlaps mozilla logo at tablet breakpoint

### ISSUE THREAD

**Issue by jpetto** [mozmeao/lumbergh#407]
At and around 700px wide, the navigation overlaps the Mozilla logo:

<img width="700" alt="Screen Shot 2019-04-08 at 9 50 13 AM" src="https://user-images.githubusercontent.com/317532/55733629-c4759800-59e3-11e9-95cd-b36fe36e7513.png">

**Comment by glogiotatidis** [comment]
With the new site redesign this is not longer valid. Thanks for reporting! :cake:
