### ISSUE TITLE
localhost:8000 in production feed links

### ISSUE THREAD

**Issue by jezdez** [mozmeao/lumbergh#411]
The careers feed at https://careers.mozilla.org/feed/ generates `<link>` items with `localhost:8000` as the hostname. This is probably related to a Django update, is my guess.

**Comment by jezdez** [comment]
Hm, or, it just needs an updated contrib sites via the admin to correctly render it. @glogiotatidis Do you want me to send a data migration to update the configured site to use the prod domain?

**Comment by jezdez** [comment]
Or maybe this is related to the static changes?

**Comment by glogiotatidis** [comment]
Indeed related to the static changes. Fixed in https://github.com/mozmeao/lumbergh/commit/64c69dfa47b21d6eef5fac482c86a4a0cbc162e5

Thanks for reporting and for offering to help @jezdez. You're the best! :cake:

**Comment by jezdez** [comment]
Thanks for the quick fix! 😻

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/pull/1088
