### ISSUE TITLE
Lighthouse says site is blocked from indexing

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/lumbergh#448]
Google Lighthouse highlighted that careers.mozilla.org might be blocked from indexing:

https://www.webpagetest.org/lighthouse.php?test=190812_SR_41b45abef0fd6361884e90c901255fe6

>  Page is blocked from indexing 
> Blocking Directive Source /robots.txt(careers.mozilla.org)

It also pointed out that the page is missing a meta description:

>  Document does not have a meta description 

![image](https://user-images.githubusercontent.com/400117/62877011-132e9800-bd1e-11e9-95a3-62e2f125a317.png)

**Comment by alexgibson** [comment]
Fwiw (obviously I do still see careers in search ^) but thought I should still file this incase it's a recent change.

**Comment by jpetto** [comment]
good catch @alexgibson! looks like this is a result of switching from jenkins to gitlab - the predefined variable containing the branch name is (unsurprisingly) different.

**Comment by jpetto** [comment]
also pinged stakeholders to provide META descriptions in our next round of updates (which should be soon).
