### ISSUE TITLE
add open graph information

### ISSUE THREAD

**Issue by jpetto** [mozmeao/lumbergh#453]

**Comment by amychurchwell** [comment]
@jpetto I'm not sure what this issue means. Is this okay to close?

**Comment by jpetto** [comment]
sorry for the lack of detail! intent was to add open graph info (image, mostly, but also descriptions & titles) so the site could have a nice representation when shared on social networks.

definitely not a high priority, but would be nice to have.

**Comment by amychurchwell** [comment]
no problem! thanks for the update! good idea, sounds like we need an asset.

**Comment by ccooper** [comment]
https://ogp.me/

**Comment by ccooper** [comment]
I'll need to use twitter's card validator once this gets deployed: https://cards-dev.twitter.com/validator
