### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by metadave** [mozmeao/lumbergh#455]
Let's rename this repo: it's hard for people to find and has some negative imagery that I'd like to get away from.

Thoughts @mozmeao/meta ?

**Comment by jpetto** [comment]
i'm on board. i don't think a horrible movie boss is the best code name. that being said, i think we should keep with tradition and find a different, more positive/fun code name rather than going boring, e.g. not `careers`.

**Comment by pmac** [comment]
I don't believe there's a fun name that won't bother someone some day. And if a goal is to make it findable then it should just be `careers` and probably moved back to the `mozilla` org. I'd like to keep this name, but if it needs to change then I vote `careers` or `careers.mozilla.org`.

**Comment by amychurchwell** [comment]
Hi all! Are we renaming lumbergh? It's unclear if we arrived at a decision. 🙂 personally, my vote would be to rename because I'm not the biggest fan of the character.

**Comment by glogiotatidis** [comment]
I'll echo @pmac on this one: I'd keep it otherwise i'd change it to careers. Let's not move orgs though.
