### ISSUE TITLE
Update existing webpages w. proper metadata

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#469]
Description:  
Update existing webpages w. proper metadata (list below)

Home
Listings
Individual Listings (pages)

***Tasks***
- [ ] Add metadata, page title and description, from [the copy](https://docs.google.com/spreadsheets/d/1Rtc7E5xL4wJXY_lmofP_-ZdvokFFAPrT-ee_5MXKs3U/edit?ts=5d167f53#gid=1544994067) here that was created w. RRaue consultation

**Comment by jpetto** [comment]
this work is already in production. see #451, #452
