### ISSUE TITLE
Survey bars cut off 

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#471]
I small part on the bottom of each bar is missing. This happened also before #468 

![image](https://user-images.githubusercontent.com/584352/64673023-c56c9300-d475-11e9-9081-ed4bfda50450.png)

**Comment by jpetto** [comment]
hmm, which browser are you using here? i just checked prod with fx nightly, fx release, safari, and chrome and see the following on all:

<img width="414" alt="Screen Shot 2019-09-16 at 3 05 50 PM" src="https://user-images.githubusercontent.com/317532/64989666-98641a00-d893-11e9-8ca5-8e42826d3b68.png">

**Comment by jpetto** [comment]
@glogiotatidis are you still seeing this issue?

**Comment by glogiotatidis** [comment]
Yap. Sorry i missed your previous comment. I'm on Linux Fx 70b11. I don't get this with a fresh nightly install or chrome. so I guess it's a snowflake error on my browser. closing this
