### ISSUE TITLE
New copy and link in modal window on careers 

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#473]
Description:
Change text in pop-up from “We’ve finished our internship hiring for Summer 2019, but please check back with us soon! We will begin accepting applications in September 2019 for Summer 2020 internships. If you’re still interested in contributing to Mozilla now, we’d love for you to get involved.”

to:

 “Summer 2020 internships are now open! Please click here to apply.” and “here” links to https://careers.mozilla.org/listings/?position_type=Intern

---

**Comment by jpetto** [comment]
confirmed in slack that we can simply remove the modal and link the "Internships" nav item directly to the URL above.
