### ISSUE TITLE
clean up old pages/assets

### ISSUE THREAD

**Issue by jpetto** [mozmeao/lumbergh#484]
after #467 is closed, all old pages on the site will have been updated, which means many templates and assets will no longer be needed. i've done my best to mark/rename/group these files with `old` in some fashion - whether in the file name itself or the containing directory.

a full sweep of the codebase should be done to ensure all unused files are removed.

**Comment by ccooper** [comment]
There is cleanup happening in #487 to get rid of jquery, so I'm waiting in line behind that. I have a simple script that walk the dir looking for files that aren't referenced that I can run once #487 lands.
