### ISSUE TITLE
Analytics audit of careers.mozilla.org

### ISSUE THREAD

**Issue by amychurchwell** [mozmeao/lumbergh#488]
![image](https://user-images.githubusercontent.com/30483988/67985424-0f583680-fbe6-11e9-81d2-1c9300ba890e.png)

**problem:**
traffic numbers as reported have dipped significantly since the redesign was launched on 8/6/2019.

**open questions:**
1) is GA working correctly on the new site? we are assuming the answer here is yes as we are getting traffic reported to GA, but maybe there’s an issue preventing ALL traffic from being accurately reported.

2) if the answer to 1) above is “yes”, why have traffic numbers dipped so significantly? were they artificially inflated before? are there any segments of visitors that have dropped off specifically, i.e. did the site change cause some visitors to not be able to load the site?

**site redesign pull request:** #433

**Comment by amychurchwell** [comment]
[`static/js/ga_event-tracking.js`](https://github.com/mozmeao/lumbergh/blob/master/careers/base/static/js/ga_event-tracking.js) is the google analytics JS for the site. In the [major site redesign pull request](https://github.com/mozmeao/lumbergh/pull/433) merged on **Aug 5**, `ga_event-tracking.js` was trimmed to remove a lot of code no longer in use. A refactor was left as [an open todo](https://github.com/mozmeao/lumbergh/pull/433#issuecomment-517455243). :+1: This issue is to address that todo item.

**Comment by ejregithub** [comment]
Eric to ask Amy about this

**Comment by amychurchwell** [comment]
@ejregithub I think this is work an external vendor could do. It is not an insignificant amount of work; there is quite a lot of cleanup needed and it might be easier to remove it all and implement from scratch.

**Comment by helfi92** [comment]
Looking at the source code, I see that we are not doing anything when a user clicks on an element that we are tracking:

https://github.com/mozmeao/lumbergh/blob/fceebbe778951cd6d4ba816ef1609e142d4f9ef7/careers/base/static/js/ga_event-tracking.js#L16-L18


Here's what we had prior to the site redesign in #433 

https://github.com/mozmeao/lumbergh/blob/fceebbe778951cd6d4ba816ef1609e142d4f9ef7/careers/base/static/js/ga_event-tracking-old.js#L13-L15

@jpetto Do you remember why this line was removed?

**Comment by hoosteeno** [comment]
I asked our GA reseller Adswerve to take a look, and here's their response:

> They do not have GTM properly implemented - it is missing the entire first part of the script. It looks like the intent was to use the GTM container "GTM-MLM3DH." 

They provided the following implementation spec for GTM:

![Screen Shot 2020-09-23 at 3 25 57 PM](https://user-images.githubusercontent.com/94519/94071539-4cef2080-fdb1-11ea-9f63-13185dc7b5d5.png)

**Comment by pmac** [comment]
Can we just steal the implementation from bedrock?

**Comment by pmac** [comment]
It seems that bedrock doesn't use the `noscript` `iframe` thing in part 2. I think we should indeed basically steal the bedrock gtm code. I can do that if you'd like.

**Comment by pmac** [comment]
Also it looks like we do have that script, they just didn't bother to look in this file that's loaded in the `<head>` https://careers.mozilla.org/static/js/gtm.e7db5fcac6df.js

**Comment by glogiotatidis** [comment]
> @jpetto Do you remember why this line was removed?

IIRC GA on careers was very broken and not being taken care of.  This specific line was tracking an scrolling event in the previous design and did not make sense to keep in the current version of the site. Apparently we never got to the point to implement what's needed for the current one. 

+1 on what @pmac said about using bedrock's gtm implementation which is the best maintained one to our liking.

**Comment by glogiotatidis** [comment]
And @pmac sent a PR before I managed to hit `comment` :100: :beers:

**Comment by ccooper** [comment]
@dianel Are you happy with the analytics on the Careers site now? Can we close this out?

**Comment by dianel** [comment]
Yes thank you!

**Comment by dianel** [comment]
hi all- i think this fixed the overall sit aanalytic but i'm not seeing *blog analytics e,g. in this report - help? https://analytics.google.com/analytics/web/#/report-home/a36116321w64880900p66602784 @TimAshton
