### ISSUE TITLE
Careers GitLab pipeline does run on weekends.

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/lumbergh#520]

**Comment by glogiotatidis** [comment]
@duallain it seems that your job run during the weekend so there something wrong with the other job.

nice job figuring it out!

![image](https://user-images.githubusercontent.com/584352/73656640-43397100-4699-11ea-864a-0310acdb8650.png)

**Comment by duallain** [comment]
It looks like this was related to the prod/production branch rename. Switched the job to the right name.
