### ISSUE TITLE
Add Glassdoor logo and link on careers.mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#528]
Add Glassdoor logo and link at the bottom of each page (in the footer if possible).

Use the Instructions at the bottom of [this document](https://docs.google.com/document/d/1JdX4VHNLjyE2RAmvqWVTPcxwcvqaLdSu40pflK6o0g4/edit?ts=5e32ae8f)

**Comment by dianel** [comment]
instructions here -> Link to Glassdoor logo at bottom (see instructions https://www.glassdoor.com/employers/ec/badges_input.htm?currentPartnerId=174673&selectedEmployerId=19129&profileId=19329 ) ->
This is the embed code -> <a href='https://www.glassdoor.com/Overview/Working-at-Mozilla-EI_IE19129.11,18.htm'><img src='https://www.glassdoor.com/pc-app/static/img/partnerCenter/badges/eng_BASIC_250x90.png'></a>
