### ISSUE TITLE
Update Meta Descriptions on careers.mozilla.org webpages

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#530]
Requirements:

- [x] On page the homepage (careers.mozilla.org), update the meta description with the following copy:

"Feel good about your work again. At Mozilla, you can pursue your future while working to protect the future of the internet for everyone, everywhere."

- [x] On https://careers.mozilla.org/listings, update the meta description with the following copy:

"We have a mighty mandate, serving hundreds of millions of people. Add a culture of exploration, and there is always a new way to learn and grow here."

**Comment by gabbyprecious** [comment]
I'll like to contribute to this, can I hop on this?

**Comment by amychurchwell** [comment]
As far as I know- these are already the meta descriptions for these pages?

**Comment by ejregithub** [comment]
You are correct, just checked, this was already done. Closing.
