### ISSUE TITLE
Update images used on careers.mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/lumbergh#531]
Requirements:

- [x] Update hero image on the homepage with [this one](https://drive.google.com/file/d/13aYsdIc0SPp1uIwXwyAIbq9XnyRwZSyZ/view?usp=sharing)

- [x] Update the internships page - https://careers.mozilla.org/internships/ - hero image with [this one
](https://drive.google.com/file/d/1AjLPfxIn5DXcoiuIvKCmBPpB8v2kx1b1/view?usp=sharing)

- [x] Update the jobs page https://careers.mozilla.org/listings/ hero image with [this one](https://lh3.googleusercontent.com/ViCH7Xo7f_YpT3AdYe-LbKXq2lwZTrxQVpPa3J0WcAU3zIXAHveUs_NZZPYIV_unpsQ0mw6nM1Ilz5hJQ81tZC7FHxxlvTg0dnHdVYVmFNZ302Wf1wjtexwLCnp84zmtyjzbvm_f4DmRfMpHN4asBCKagrrjMmK7GKcqFu8KK5hyhGaZD5yXg56H-NvNhjG1wO4zFF8uJ9k5X-nyEVC0yg-hDRMmKDgDGy5zRLzK_mRl4nUP4vmFZYNkVZm-rnYlNis3BjCxZuZLovl28tlaMo7cApnZPxFmzS95HZcMlcveZPU8BzG4z-Hl9a1Lx_UcGMx9FbNGVN6yUT2yuUlaflrRcLXDJOEJiTcfDbbaBv0wcQI938BiEaHAddflvqurUHjZ1lzJdyGQ54GlxePc62mWxoekzInG4pW5Erx8tOe4-t-YWms5jXWA9wwwFv1Gl-lPTgJtmc1d2tnEvVq_DjaCokBB6s8e7ZJm2tUBWmDaMEUSVSeScnWke-wIwj8FmWTPErCnctVeY7zXZ9S--zX5HuyItBYtzK4e_x-EA7DNLfdV8FVqLvkHo49wmxNHHJBKiRbE3J9m3BYQLePJt1l0ea4_0CVw2_8A-ZCn_lnCnbd6R_61iGD2ynrZP6ApNeTQ31w5D-kmvB7wGdailsM_MgqBOUIsbGT0AbmKPBoFvBM9gmRZxD9Xm0k2=k-ft)

- [x] (Determine feasibility, effort required first) For each job listing page use [this hero image](https://drive.google.com/file/d/1SLAATauDCBnt4jr2BnggkEQhOcOPnB9d/view?usp=sharing)

**Comment by amychurchwell** [comment]
@ejregithub The image provided for /listings seems a lot lower resolution than the other images. By that I don't mean that the photo is too small, it just seems to be taken at a lower quality. I will update as requested, but there is a noticeable quality difference.
