### ISSUE TITLE
Tone deaf wording

### ISSUE THREAD

**Issue by crstpierre** [mozmeao/lumbergh#562]
Description of the work requested: Updates to careers.mozilla.org main page

RASCI
R - Eric
A - Mardi
S - Amy and another dev TBD to review
C - Chris and ?
I - NA

#### Success Criteria
- [x] All Hands video link has been updated
- [x] Copy below All Hands video has been replaced w. new copy and link to blog
- [ ] Tara image and copy has been replaced, w. new image, copy and link
- [x] Copy below engagement survey results has been replaced
- [x] Mardi has reviewed/approved prior to go live

#### Approvers
- [x] Accountable - Mardi

**Comment by crstpierre** [comment]
I'm going to expand on this request after a chat with internal comms, thank you!

**Comment by mardid** [comment]
Here is the [new video link] (https://youtu.be/_EeFDE5WW0I). Please wait to add until we reopen this ticket but putting here so we have it.

**Comment by mardid** [comment]
Updated copy to go beneath the hero video above:
**Because sometimes we zoom**
Since March of this year, like so many of our peers, we closed our offices and asked just over ½ of our employees, for their safety, to head home to work (the other ½ was already there). And we are all [doing the best we can](https://blog.mozilla.org/careers/working-from-home-at-mozilla/).

**Comment by mardid** [comment]
Also to update, copy beneath the engagement survey results:
**Our culture ensures our future**
Our July 2019 employee survey confirms respect for one another and an emphasis on learning and innovation are what will ensure our future.

**Comment by crstpierre** [comment]
Also to update, diversity photo and copy below the hero video/copy (photo attached).

**Diversity and Inclusion At Mozilla**
We’ve made some progress that we’re proud of, and we have a lot more work to do.
**[Learn More](https://blog.mozilla.org/careers/mozilla-diversity-inclusion-2019-results/)**

![diversity-disclosure](https://user-images.githubusercontent.com/42879770/84172841-4ec6eb00-aa31-11ea-897a-76e7347af824.png)

**Comment by dianel** [comment]
we opened a new issue for the one remaining item so will close this one out

**Comment by dianel** [comment]
we can close this issue
