### ISSUE TITLE
Update Employee Engagement Survey data on home page

### ISSUE THREAD

**Issue by dianel** [mozmeao/lumbergh#606]
Our hoome page currently has outdated employee engagement survey info. We hope to replace this section:

![image](https://user-images.githubusercontent.com/1105494/92013253-5d583200-ed02-11ea-82f3-0e24177b68dd.png)

with this data/imagery:
![image](https://user-images.githubusercontent.com/1105494/92013315-7365f280-ed02-11ea-99ae-d2f29d9a63c1.png)

and this text:
**Our culture**
Our June 2020 employee survey highlights our respect for one another and an emphasis on learning and development.

**Comment by dianel** [comment]
oops here are all the new images:
![image](https://user-images.githubusercontent.com/1105494/92013431-9e504680-ed02-11ea-9dbb-9a9a7130b17e.png)
![image](https://user-images.githubusercontent.com/1105494/92013440-a1e3cd80-ed02-11ea-8b30-0ad16104f677.png)
![image](https://user-images.githubusercontent.com/1105494/92013450-a5775480-ed02-11ea-92b6-55ff64131793.png)

**Comment by dianel** [comment]
(we may need a designer!)

**Comment by ccooper** [comment]
I think we could probably route around the need for a designer and make this easier to maintain going forward if we switch from image assets to a pure CSS approach. There are lots of examples of horizontal stacked bar charts made using CSS. Here's a particularly simple one: https://codepen.io/villa7/pen/YqmjKQ?editors=1100

Updating it in the future would involve changing a few numbers, and the styling could be updated easily too.

@helfi92 Is this a reasonable approach? Looking for a sanity check here.

**Comment by helfi92** [comment]
Yes, that is a very reasonable approach even more preferable.

**Comment by ccooper** [comment]
LOL, I just looked at the page framework and it's already setup this way.
