### ISSUE TITLE
update employee engagement survey data on careers home page

### ISSUE THREAD

**Issue by gitbiz** [mozmeao/lumbergh#652]
Wehave October 2020 data - please update using same CSS approach done in https://github.com/mozmeao/lumbergh/issues/606 as follows:

https://mail.google.com/mail/u/0?ui=2&ik=336832fee2&attid=0.3&permmsgid=msg-f:1685439967058935675&th=1763e2b85ecb3f7b&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ9xV2Et2yrI_FpBikiBsjY7kcQkM2RS7s7fEhdvehYA2OFyghcmh3E2oC-nuVsxsyqb_9hRJU9K1-F7U46YDarId83DI_7TNP5bOtopkINJxaFxe1cykkbTSVY&disp=emb&realattid=ii_kiesviae2

https://mail.google.com/mail/u/0?ui=2&ik=336832fee2&attid=0.4&permmsgid=msg-f:1685439967058935675&th=1763e2b85ecb3f7b&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ9jdF7Z8UntdyX7YhtHTwq0yldMetbDOceeGF11SXpEBejn-CDfCWpYOibjiLR-ukXh5mbAZtAeKCI0_PInypJRSEUBTeGeuA9fLad1Gcr7Kvk6OWPMOCpjqow&disp=emb&realattid=ii_kiet1kwv3
^^ with shortened text to just: "Within my organization, I feel psychologically safe."

and

https://mail.google.com/mail/u/0?ui=2&ik=336832fee2&attid=0.5&permmsgid=msg-f:1685439967058935675&th=1763e2b85ecb3f7b&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ_DRecX3iRjLdbIZUtdHfCdQJo8B-4w_h9jO1o7Bn5vLZIkt2i81H8fc_5mHaGB2bYO7j_cQFwumUu4KnvrIPGPiyXXFKXdbJ6WJp0xtXK1etQ6kQCwVKiza1s&disp=emb&realattid=ii_kiet38h14

**Comment by dianel** [comment]
do thesee work? 
![Screenshot_2021-03-29 unnamed png (PNG Image, 604 × 82 pixels)](https://user-images.githubusercontent.com/1105494/112882085-5b303900-9081-11eb-8644-aa5d90ad6f74.png)
![Screenshot_2021-03-29 unnamed png (PNG Image, 675 × 212 pixels)](https://user-images.githubusercontent.com/1105494/112882087-5bc8cf80-9081-11eb-9648-0655968f5b30.png)
![Screenshot_2021-03-29 unnamed png (PNG Image, 672 × 65 pixels)](https://user-images.githubusercontent.com/1105494/112882093-5cf9fc80-9081-11eb-8800-fdc4b26f5505.png

**Comment by dianel** [comment]
![Screenshot_2021-03-29 unnamed png (PNG Image, 672 × 65 pixels)](https://user-images.githubusercontent.com/1105494/112882175-7ac76180-9081-11eb-978c-cdb61b43693f.png)

**Comment by dianel** [comment]
ok we're gonna use these three responses -- date is September 2020:
![image](https://user-images.githubusercontent.com/1105494/113636163-e633a500-9626-11eb-99e7-9f104fa54354.png)

![image](https://user-images.githubusercontent.com/1105494/113636186-ef247680-9626-11eb-8b9b-b76ddb8d876e.png)
(we can end the text after "safe" to ensure the ? doesn't run too long)

and 
![image](https://user-images.githubusercontent.com/1105494/113636224-fcd9fc00-9626-11eb-8a7b-2a47ac72a0dd.png)

**Comment by dianel** [comment]
woohooo - do we get a ping when it's live on the site @pmac ?

**Comment by pmac** [comment]
When it merges it gets deployed to the staging site: careers.allizom.org 

When that gets a look and is approved someone should ping me to push it to production.

**Comment by dianel** [comment]
lovely thank you @pmac
