### ISSUE TITLE
add metadata to display images for thumbnails

### ISSUE THREAD

**Issue by dianel** [mozmeao/lumbergh#689]
adding an image to the metadata of the careers page so that it will show up in Twitter mentions

let's use a mozilla logo image?

More info at https://css-tricks.com/essential-meta-tags-social-media/

**Comment by TimAshton** [comment]
The Open Graph spec defines the og:image as a "URL" which contains the protocol, so relative paths are not expected to work, (even though it MAY, based on the social service consuming it). We currently have a relative path. This fix adds the careers site URL to the front of the og:image content attribute for both general and Twitter use.

Open Graph source:
https://ogp.me/
