### ISSUE TITLE
Add a new positions RSS feed

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/lumbergh#691]
The careers feed at https://careers.mozilla.org/feed/ publishes all current listing by modification date. This means that when a listing is updated, for example to fix a typo, an existing listing jumps to the most recent spot. This causes tools, such as a Slack RSS scraper, to post the same job multiple times as it is edited.

It would be useful to have an alternate feed, such as https://careers.mozilla.org/feed-new/, that reports jobs in the order they are first posted.

This would require expanding the ``Position`` model to add a ``created_at`` or ``first_seen`` timestamp to go along with ``updated_at``:

https://github.com/mozmeao/lumbergh/blob/6a5dfee8ff9ae29d9e1b8e36a5de6321d7433644/careers/careers/models.py#L20

The [Greenhouse Job Board API](https://developers.greenhouse.io/job-board.html#retrieve-a-job) does not expose when a job was first created, so we couldn't get it from the API. Instead, something like this would work:

 1. Set ``created_at`` for existing positions to their ``updated_at`` value, and 
 2. Set ``created_at`` when the Greenhouse synced first sees a position:
 
https://github.com/mozmeao/lumbergh/blob/906bd4a896f4bdcfb71da105881b3eae2b246ed8/careers/careers/management/commands/sync_greenhouse.py#L58-L59

The new positions feed could extend the existing ``LatestPositionsFeed`` by overriding the ``item_pubdate``:

https://github.com/mozmeao/lumbergh/blob/6a5dfee8ff9ae29d9e1b8e36a5de6321d7433644/careers/careers/feeds.py#L38-L39

**Comment by TimAshton** [comment]
Moved to the new PRD and will be re-added in that context.
