### ISSUE TITLE
Update the URL for the Applicant Privacy Notice

### ISSUE THREAD

**Issue by pmac** [mozmeao/lumbergh#790]
There is an "Applicant Privacy Notice" link at the bottom of the job description page, under the "Apply for this job" button. This link should be updated to match the URL to which the [privacy notice](https://docs.google.com/document/d/e/2PACX-1vTEeCImDA-kqr0wm3JwfOv_2MS5FZ8oyL2pEWfVsZbeO87E41r2wePoOhppQ4qX6w/pub) links from the Greenhouse page.

**Comment by joneskj55** [comment]
Hi @pmac I have the environment spun up and running. However, I'm not sure which URL should be placed in `position.jinja` I assume you don't want the Google Doc as the link but I don't know where the PDF is located.

**Comment by pmac** [comment]
We do want the google doc link this time actually. It's what they've used on the application in greenhouse. We plan on having a better more permanent home for this doc soon.
